#include "lex.h"
#include "tree.h"
#include "token.h"

#ifndef PARSER
#define PARSER

// Parser for the Lambda Calculus language.
class Parser{

public:

    // a function to read a token and apply the language rules
    void parse(std::string expression);

    // getter for bool passed
    bool getPassed(){
        return passed;
    }

private:

    // functions

    // Calls function expr. When expr returns it will check if all tokens
    // have been handled, if not raise error.
    void start();

    // Parses strings in the language generated by the rule:
    // ⟨expr⟩ ::= VAR ⟨expr_⟩ | '(' ⟨expr⟩ ')' ⟨expr_⟩ | '\' VAR ⟨expr⟩ ⟨expr_⟩
    Node* expr();

    // ⟨expr_⟩ ::=  VAR ⟨expr_⟩ | '(' ⟨expr⟩ ')' ⟨expr_⟩ | '\' VAR ⟨expr⟩ ⟨expr_⟩ | empty string
    Node* expr_(); 

    // 
    void error();

    // Builds a subtree with an @ if right is not a nullptr
    Node* buildSubTree(Node* left, Node* right);

    // variables
    
    Token nextToken;
    bool passed = true; // a variable that keeps track if the parser detected errors
                        // true if no errors, false if errors.

    Lex lex; // lexical analyser used by the parser

    std::string currentExpression;

    Tree ast; // abstract syntax tree


};

#endif